url_shortener/models.py
import string
from datetime import datetime
from random import choices


from .extensions import db

class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_url = db.Column(db.String(3), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()

    def generate_short_link(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=3))

        link = self.query.filter_by(short_url=short_url).first()

        if link:
            return self.generate_short_link()
            
        return short_url

url_shortener/__init__.py
from flask import Flask 

from .extensions import db
from .routes import short

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    app.register_blueprint(short)

    return app

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .models import Link

from .extensions import db

short = Blueprint('short',__name__)

@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()

    link.visits += 1
    db.session.commit()
    return redirect(link.original_url)

@short.route('/')
def index():
    return render_template('index.html')

@short.route('/add_link', methods = ['POST'])
def add_link():
    original_url =request.form['original_url']
    link = Link(original_url=original_url)
    db.session.add(link)
    db.session.commit()

    return render_template('link_added.html',
        new_link = link.short_url, original_url=link.original_url)

@short.route('/stats')
def stats():
    links = Link.query.all()

    return render_template('stats.html', links=links)

@short.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

url_shortener/templates/index.html
<head>
    <title>Flask app</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css.css') }}">
</head>
<nav>
    <h1>VELINK SHORTENER</h1>
    <img src="https://avatars.githubusercontent.com/u/70204648?v=4">
</nav>
<div id="home">
<h2 id="enter"> Enter a URL you would like to shorten!</h2>
<form method = 'POST' action = "{{ url_for('short.add_link') }}">
    <input type = "text" name = "original_url" id="url_input">
    <input type="submit" id="url_submit">
</form>
</div>

url_shortener/templates/link_added.html
<head>
    <title>Flask app</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css.css') }}">
</head>

<nav>
    <h1>VELINK SHORTENER</h1>
    <img id = "short-velink" src="https://avatars.githubusercontent.com/u/70204648?v=4">
</nav>

<div id = 'links'>
    <h2>Here are your velinks!</h2>
<div id ='align'>
Old Velink: {{ original_url }} <br/>
<div id='new-link'>
New Velink: <a id = "myInput" href="{{ url_for('short.redirect_to_url', short_url=new_link, _external=True) }}">{{ url_for('short.redirect_to_url', short_url=new_link, _external=True) }}</a>
<button id="copy" onclick="myFunction()">Copy link</button>
</div>
</div>
</div>
<script src="{{ url_for('static', filename='/copy.js') }}"></script>

url_shortener/templates/stats.html
<link rel="stylesheet" href="{{url_for('static, filename='/css.ss')}}">

{%for link in links %}
Original Url:  {{link.original_url}} - 
Short URL: {{ link.short_url}} - 
Visits: {{ link.visits}}
<br/>
{% endfor %}